

export const SERVICE_DURATION_MIN = 5;
export const SERVICE_DURATION_MAX = 240;

export const BOOKING_MIN_NOTICE_HOURS_DEFAULT = 2;
export const BOOKING_MAX_FUTURE_DAYS_DEFAULT = 90;
export const BOOKING_CANCELLATION_CUTOFF_DEFAULT = 24;

export const SPEAKING_SPEED_MIN = 0.8;
export const SPEAKING_SPEED_MAX = 1.2;
export const SPEAKING_SPEED_DEFAULT = 1.0;

export const FAQ_CONFIDENCE_THRESHOLD_DEFAULT = 0.75;
export const FAQ_CONFIDENCE_THRESHOLD_MIN = 0.0;
export const FAQ_CONFIDENCE_THRESHOLD_MAX = 1.0;

export const CALL_MAX_TURNS_DEFAULT = 30;
export const CALL_COST_ANOMALY_THRESHOLD_USD = 5.0;

export const RATE_LIMIT_API_DEFAULT = 1000;
export const RATE_LIMIT_AUTH_LOGIN = 5;
export const RATE_LIMIT_WEBHOOK = 200;
export const RATE_LIMIT_CONFIG_WRITE = 30;
export const RATE_LIMIT_ANALYTICS_READ = 60;

export const CACHE_TTL_PHONE_MAPPING = 300;
export const CACHE_TTL_TENANT_CONFIG = 300;
export const CACHE_TTL_PROVIDER_HEALTH = 60;

export const ACCESS_TOKEN_EXPIRY_SECONDS = 900;
export const REFRESH_TOKEN_EXPIRY_DAYS = 7;

export const PROVIDER_HEALTH_CHECK_INTERVAL_MS = 30_000;
export const PROVIDER_MIN_SUCCESS_RATE = 0.95;
export const PROVIDER_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5;
export const PROVIDER_CIRCUIT_BREAKER_RECOVERY_TIMEOUT_S = 30;

export const SCORING_WEIGHT_COST = 0.40;
export const SCORING_WEIGHT_LATENCY = 0.35;
export const SCORING_WEIGHT_RELIABILITY = 0.25;

export const LATENCY_BUDGET_WEBHOOK_PROCESSING = 100;
export const LATENCY_BUDGET_TENANT_RESOLUTION_CACHED = 10;
export const LATENCY_BUDGET_TENANT_RESOLUTION_DB = 50;
export const LATENCY_BUDGET_CONFIG_LOADING_CACHED = 20;
export const LATENCY_BUDGET_CONFIG_LOADING_DB = 100;
export const LATENCY_BUDGET_STT = 300;
export const LATENCY_BUDGET_AI_REASONING = 800;
export const LATENCY_BUDGET_TOOL_EXECUTION = 2000;
export const LATENCY_BUDGET_TTS = 400;
export const LATENCY_BUDGET_TURN_TOTAL = 1500;

export const COST_MARGIN_PERCENT_DEFAULT = 30;

export const PROMPT_TOKEN_BUDGET = 6000;
export const PROMPT_TURN_HISTORY_WINDOW = 10;
export const PROMPT_FAQ_TOP_N = 10;
